-- bdd : PostgreSQL
CREATE TABLE delta
(
    id SERIAL PRIMARY KEY,
    coeff_a DOUBLE PRECISION NOT NULL,
    coeff_b DOUBLE PRECISION NOT NULL,
    coeff_c DOUBLE PRECISION NOT NULL,

    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);