sonar.projectKey=Lee-Rudy_microservice6
sonar.organization=lee-rudy
sonar.projectName=microservice6
sonar.projectVersion=1.0

sonar.sources=src/project
sonar.tests=tests

sonar.python.version=3.13
sonar.sourceEncoding=UTF-8

sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.python.xunit.reportPath=reports/tests.xml

sonar.coverage.exclusions=tests/**,**/__init__.py