sonar.projectKey=Lee-Rudy_microservice6
sonar.organization=lee-rudy
sonar.sources=src
sonar.tests=tests
sonar.python.version=3.13
sonar.python.coverage.reportPaths=reports/coverage.xml
sonar.sourceEncoding=UTF-8